-- Database Schema for QuoteVault
-- Run this in your Supabase SQL Editor

-- Enable Row Level Security
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

-- Create quotes table
CREATE TABLE public.quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  author text,
  category text NOT NULL CHECK (category IN ('Motivation', 'Love', 'Success', 'Wisdom', 'Humor')),
  created_at timestamptz DEFAULT now()
);

-- Create user_favorites table
CREATE TABLE public.user_favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  quote_id bigint REFERENCES public.quotes(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, quote_id)
);

-- Create collections table
CREATE TABLE public.collections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Create collection_quotes table (many-to-many)
CREATE TABLE public.collection_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id bigint REFERENCES public.collections(id) ON DELETE CASCADE,
  quote_id bigint REFERENCES public.quotes(id) ON DELETE CASCADE,
  UNIQUE(collection_id, quote_id)
);

-- Create profiles table for user settings
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) PRIMARY KEY,
  display_name text,
  avatar_url text,
  settings jsonb DEFAULT '{
    "theme": "light",
    "accentColor": "#007AFF",
    "fontSize": "medium",
    "notificationsEnabled": true,
    "notificationHour": 9
  }'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for quotes (public read)
CREATE POLICY "Quotes are viewable by everyone" ON public.quotes
  FOR SELECT USING (true);

-- RLS Policies for user_favorites (user-specific)
CREATE POLICY "Users can view their own favorites" ON public.user_favorites
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own favorites" ON public.user_favorites
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites" ON public.user_favorites
  FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for collections (user-specific)
CREATE POLICY "Users can view their own collections" ON public.collections
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own collections" ON public.collections
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own collections" ON public.collections
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own collections" ON public.collections
  FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for collection_quotes (user-specific via collections)
CREATE POLICY "Users can view quotes in their collections" ON public.collection_quotes
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.collections
      WHERE collections.id = collection_quotes.collection_id
      AND collections.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can add quotes to their collections" ON public.collection_quotes
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.collections
      WHERE collections.id = collection_quotes.collection_id
      AND collections.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can remove quotes from their collections" ON public.collection_quotes
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.collections
      WHERE collections.id = collection_quotes.collection_id
      AND collections.user_id = auth.uid()
    )
  );

-- RLS Policies for profiles (user-specific)
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (new.id, new.raw_user_meta_data->>'name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create profile on user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Create indexes for better performance
CREATE INDEX idx_quotes_category ON public.quotes(category);
CREATE INDEX idx_user_favorites_user_id ON public.user_favorites(user_id);
CREATE INDEX idx_collections_user_id ON public.collections(user_id);
CREATE INDEX idx_collection_quotes_collection_id ON public.collection_quotes(collection_id);