-- Seed Quotes Data
-- Run this in Supabase SQL Editor after running schema.sql

-- Insert all quotes in one go
INSERT INTO public.quotes (text, author, category) VALUES
-- Motivation (25 quotes)
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Motivation'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'Motivation'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'Motivation'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'Motivation'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'Motivation'),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Motivation'),
('The best way to predict the future is to create it.', 'Peter Drucker', 'Motivation'),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', 'Motivation'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'Motivation'),
('Keep your face always toward the sunshine—and shadows will fall behind you.', 'Walt Whitman', 'Motivation'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'Motivation'),
('Don''t let yesterday take up too much of today.', 'Will Rogers', 'Motivation'),
('The secret of getting ahead is getting started.', 'Mark Twain', 'Motivation'),
('Everything you can imagine is real.', 'Pablo Picasso', 'Motivation'),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Anonymous', 'Motivation'),
('Dream it. Wish it. Do it.', 'Anonymous', 'Motivation'),
('Whatever you are, be a good one.', 'Abraham Lincoln', 'Motivation'),
('Never give up on a dream just because of the time it will take to accomplish it.', 'Anonymous', 'Motivation'),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Motivation'),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'Motivation'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Motivation'),
('Go confidently in the direction of your dreams.', 'Henry David Thoreau', 'Motivation'),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'Motivation'),
('The mind is everything. What you think you become.', 'Buddha', 'Motivation'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'Motivation'),

-- Love (20 quotes)
('Love is not just looking at each other, it''s looking in the same direction.', 'Antoine de Saint-Exupéry', 'Love'),
('The best thing to hold onto in life is each other.', 'Audrey Hepburn', 'Love'),
('Love recognizes no barriers.', 'Maya Angelou', 'Love'),
('Where there is love there is life.', 'Mahatma Gandhi', 'Love'),
('Love is composed of a single soul inhabiting two bodies.', 'Aristotle', 'Love'),
('The greatest happiness of life is the conviction that we are loved.', 'Victor Hugo', 'Love'),
('Love is when the other person''s happiness is more important than your own.', 'H. Jackson Brown Jr.', 'Love'),
('A successful marriage requires falling in love many times, always with the same person.', 'Mignon McLaughlin', 'Love'),
('Love doesn''t make the world go ''round. Love is what makes the ride worthwhile.', 'Franklin P. Jones', 'Love'),
('Being deeply loved by someone gives you strength.', 'Lao Tzu', 'Love'),
('Love is the only force capable of transforming an enemy into a friend.', 'Martin Luther King Jr.', 'Love'),
('The heart has its reasons which reason knows not.', 'Blaise Pascal', 'Love'),
('Love cures people—both the ones who give it and the ones who receive it.', 'Karl A. Menninger', 'Love'),
('True love is eternal, infinite, and always like itself.', 'Honore de Balzac', 'Love'),
('Love is friendship that has caught fire.', 'Joseph Campbell', 'Love'),
('The most important thing in life is to learn how to give out love, and to let it come in.', 'Morrie Schwartz', 'Love'),
('Love is not finding someone to live with, it''s finding someone you can''t live without.', 'Rafael Ortiz', 'Love'),
('There is no remedy for love but to love more.', 'Henry David Thoreau', 'Love'),
('Love makes your soul crawl out from its hiding place.', 'Zora Neale Hurston', 'Love'),
('To love and be loved is to feel the sun from both sides.', 'David Viscott', 'Love'),

-- Success (20 quotes)
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Success'),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'Success'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'Success'),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'Success'),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', 'Success'),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'Success'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Success'),
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'Success'),
('Success consists of going from failure to failure without loss of enthusiasm.', 'Winston Churchill', 'Success'),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller', 'Success'),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'Success'),
('Try not to become a man of success. Rather become a man of value.', 'Albert Einstein', 'Success'),
('Success is liking yourself, liking what you do, and liking how you do it.', 'Maya Angelou', 'Success'),
('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'Success'),
('Success is the sum of small efforts, repeated day in and day out.', 'Robert Collier', 'Success'),
('Success is not measured by what you accomplish, but by the opposition you have encountered.', 'Anonymous', 'Success'),
('The difference between a successful person and others is not a lack of strength.', 'Anonymous', 'Success'),
('Success is peace of mind which is a direct result of self-satisfaction in knowing you did your best.', 'John Wooden', 'Success'),
('Success is getting what you want. Happiness is wanting what you get.', 'Dale Carnegie', 'Success'),
('The key to success is to focus our conscious mind on things we desire.', 'Brian Tracy', 'Success'),

-- Wisdom (20 quotes)
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Wisdom'),
('Knowledge speaks, but wisdom listens.', 'Jimi Hendrix', 'Wisdom'),
('The wise man does not lay up his own treasures.', 'Anonymous', 'Wisdom'),
('Wisdom is the right use of knowledge. To know is not to be wise.', 'Charles Spurgeon', 'Wisdom'),
('The fool wonders, the wise man asks.', 'Benjamin Disraeli', 'Wisdom'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'Wisdom'),
('The wise learn many things from their enemies.', 'Aristophanes', 'Wisdom'),
('It is wiser to find out than to suppose.', 'Mark Twain', 'Wisdom'),
('Wisdom begins in wonder.', 'Socrates', 'Wisdom'),
('The wise man sees in the misfortune of others what he should avoid.', 'Anonymous', 'Wisdom'),
('Wisdom is the daughter of experience.', 'Leonardo da Vinci', 'Wisdom'),
('A wise man can learn more from a foolish question than a fool can learn from a wise answer.', 'Bruce Lee', 'Wisdom'),
('The wise man does at once what the fool does finally.', 'Niccolò Machiavelli', 'Wisdom'),
('Wisdom is knowing when to speak your mind and when to mind your speech.', 'Anonymous', 'Wisdom'),
('The wiser you get, the less you need to prove.', 'Anonymous', 'Wisdom'),
('Wisdom comes from experience. Experience is often a result of lack of wisdom.', 'Terry Pratchett', 'Wisdom'),
('The heart of the wise is in the house of mourning.', 'Anonymous', 'Wisdom'),
('Wisdom is the power to put our time and our knowledge to the proper use.', 'Thomas J. Watson', 'Wisdom'),
('The wise man avoids evil by anticipating it.', 'Anonymous', 'Wisdom'),
('Wisdom consists of the anticipation of consequences.', 'Norman Cousins', 'Wisdom'),

-- Humor (20 quotes)
('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Anonymous', 'Humor'),
('I''m reading a book on anti-gravity. It''s impossible to put down!', 'Anonymous', 'Humor'),
('I used to play piano by ear, but now I use my hands.', 'Anonymous', 'Humor'),
('Why don''t scientists trust atoms? Because they make up everything!', 'Anonymous', 'Humor'),
('I told my computer I needed a break, and now it won''t stop sending me Kit Kat ads.', 'Anonymous', 'Humor'),
('Parallel lines have so much in common. It''s a shame they''ll never meet.', 'Anonymous', 'Humor'),
('I have a joke about trickle-down economics, but 99% of you won''t get it.', 'Anonymous', 'Humor'),
('My wife accused me of cheating. I told her she was starting to sound like my phone''s predictive text.', 'Anonymous', 'Humor'),
('I''m so good at sleeping that I can do it with my eyes closed.', 'Anonymous', 'Humor'),
('I asked my dog what''s two minus two. He said nothing.', 'Anonymous', 'Humor'),
('My therapist says I have a preoccupation with vengeance. We''ll see about that.', 'Anonymous', 'Humor'),
('I threw a boomerang at a ghost. It came back to haunt me.', 'Anonymous', 'Humor'),
('I have a joke about trickle-down economics, but 99% of you won''t get it.', 'Anonymous', 'Humor'),
('My math teacher called me average. How mean!', 'Anonymous', 'Humor'),
('I used to be a baker, but I couldn''t make enough dough.', 'Anonymous', 'Humor'),
('I''m reading a book on teleportation. It''s bound to take me places.', 'Anonymous', 'Humor'),
('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Anonymous', 'Humor'),
('Why did the scarecrow win an award? Because he was outstanding in his field!', 'Anonymous', 'Humor'),
('I have a joke about trickle-down economics, but 99% of you won''t get it.', 'Anonymous', 'Humor'),
('Time flies like an arrow; fruit flies like a banana.', 'Groucho Marx', 'Humor');

-- Verify the data was inserted
SELECT
  category,
  COUNT(*) as count
FROM public.quotes
GROUP BY category
ORDER BY category;